---
title: "Week3Assignment"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(shiny)

data <- read_csv(url("https://www.dropbox.com/s/4ebgnkdhhxo5rac/cel_volden_wiseman%20_coursera.csv?raw=1"))

data$Party <- recode(data$dem,`1`="Democrat",`0`="Republican")


#######HINT: for Chart D, you'll need to set the height of the renderPlot, using the height argument. Try a value of 750.

#####some data management functions are already included. You need to add the visualization functions.

```


Page 1
=====================================

### Chart A


```{r}
data %>% 
  drop_na() %>% 
  filter(year>1979) %>% 
  group_by(year,Party) %>% 
  summarise(passed = sum(all_pass)) %>% 
  ggplot(., aes(x = year,y = passed, fill = Party)) + 
    geom_area() + 
    labs( title = "Number of Bills Passed Since 1980", 
          x = "Year", 
          y = "All Bills Passed" ) +
    scale_fill_manual(values=c("Blue","Red")) 
```

Page 2
=====================================


Column 
-------------------------------------

### Chart B

```{r}
renderPlotly(
  data %>%
  drop_na() %>%
  filter(congress == 110) %>%
  ggplot(., aes(x = votepct, y = all_pass, group = Party, color = Party)) + 
    geom_point() + 
    geom_smooth() + 
    labs( title = "Passage and Vote Pct., 110th Congress", 
          x = "Vote Pct.", 
          y = "All Pass" ) +
    scale_color_manual(values=c("Blue","Red"))
)
```

Column 
-------------------------------------

### Chart C

```{r}
renderPlotly(
  data %>%
  drop_na() %>%
  filter(congress == 110) %>%
  ggplot(., aes(x = dwnom1, y = all_pass, group = Party, color = Party)) + 
    geom_point() + 
    geom_smooth(method = "lm") + 
    labs( title = "Passage and Ideology, 110th Congress", 
          x = "DW Nominate", 
          y = "All Pass" ) +
    scale_color_manual(values=c("Blue","Red")) 
)
```

Page 3
=====================================

Input {.sidebar}
----------------

```{r}
selectInput(inputId = "State", 
            label = "State",
            choices = unique(data$st_name),
            multiple = TRUE,
            selected = unique(data$st_name)
            )
```

Column 
-------------------------------------

### Chart D

```{r}
renderPlot(
    ggplot(data %>% 
      filter(st_name %in% input$State, congress == 110) %>%
      group_by(st_name) %>% 
      summarise(passed = sum(all_pass)),
        aes(x = passed, y = st_name)) + 
      geom_bar( stat = "identity" ) + 
      labs( title = "Total Bills Passed by State Delegations, 110th Congress",
           x = "Total Bills Passed Per State",
           y = "State Name" )
)
```
